FROM python:3.9.17-slim-bullseye
LABEL maintainer="mainforce <isu18390@gmail.com>"

ENV SERVICE_NAME hello_service

COPY ./print_hello_service /app
WORKDIR /app

RUN apt update
RUN python3 -m pip install numpy

ENTRYPOINT ["python3"]
CMD ["print_hello.py"]