FROM python:3.9.17-slim-bullseye
LABEL maintainer="mainforce <isu18390@gmail.com>"

COPY ./print_bye_service /app
WORKDIR /app

RUN apt update
RUN python3 -m pip install flask

EXPOSE 8888

CMD ["flask", "run", "--host=0.0.0.0", "--port=8888"]
